name: Docker Image CI - Consumer

on:
  push:
    paths:
      - 'lab_1/consumer-app/**/*.py'
    branches: [ "main" ]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [editorconfig, linter]
    steps:
      - name: "Checkout github action"
        uses: actions/checkout@v3
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker
        uses: azure/docker-login@v1
        with:
          login-server: tpiuoregistry.azurecr.io 
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build -t tpiuoregistry.azurecr.io/consumer-app:latest ${{ github.workspace }}/lab_1/consumer-app
          docker push tpiuoregistry.azurecr.io/consumer-app:latest

      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: consumer-app
          appSourcePath: ${{ github.workspace }}/lab_1/consumer-app
          acrName: tpiuoregistry
          resourceGroup: fervjestina
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
